trainingInput:
  scaleTier: CUSTOM
  masterType: standard_gpu
  workerType: complex_model_m
  parameterServerType: large_model
  workerCount: 5
  parameterServerCount: 2
  args:
    gs://modified-mnist-bucket/train_x.csv,
    gs://modified-mnist-bucket/train_y.csv,
